name: Mirror Code to Codeberg
on:
  push:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 
      - uses: lissy93/repo-mirror-action@main
        with:
          ssh_key: ${{ secrets.MIRROR_SSH }}
          host: git@codeberg.org
          user: jksalcedo
          repo: tend
          force_push: true
